#define F_PERCENTAGE(x) std::fixed << std::setprecision(0) << (x)
#define F_FREEDOM(x) std::fixed << (x)
#define F_VARIANCE(x) std::scientific << std::setprecision(6) << (x)
#define F_CHI_SQ(x) std::scientific << std::setprecision(6) << (x)
#define F_F_STAT(x) std::fixed << std::setprecision(4) << (x)
#define F_P_OBS(x) std::scientific << std::setprecision(4) << (x)
#define F_N(x) (x)
#define F_SAMPLE(x) F_VARIANCE(x)
#define F_SAMPLE_SQ(x) F_SAMPLE(x)
#define F_STDDEV(x) F_VARIANCE(x)
#define F_TEST_STAT(x) std::scientific << std::setprecision(7) << (x)
#define F_T(x) F_TEST_STAT(x)
